### ISSUE TITLE
Issue importing encode_query

### ISSUE THREAD

**Issue by hugomd** [Hazealign/tweetbot-alfred-workflow#1]
When creating a new tweet:   

```
[2016-08-16 12:38:39][ERROR: action.script] Traceback (most recent call last):
  File "<string>", line 13, in <module>
  File "<string>", line 5, in post_tweet
NameError: global name 'encode_query' is not defined
```

The workflow doesn't seem to pick up `encode_query()` at all. I've worked around this by downloading `tweetbot.py` and putting it in the workflow folder, and then adding `from tweetbot import encode_query` to the scripts.

**Comment by Nebu1eto** [comment]
Thanks for your report.
Can you tell your python and Alfred version for me?
Its working on my devices, so I have to test it on new virtual machine.

**Comment by hugomd** [comment]
Using the macOS default version of Python, 2.7.12, and  Alfred version 3.0.3.

**Comment by Nebu1eto** [comment]
Thanks, I'll check it.
